server:
  port: 8443
  address: 0.0.0.0
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_PASSWORD:password}
    key-password: ${SSL_KEY_PASSWORD:password}

spring:
  config:
    import: #optional:aws-secretsmanager:shopping-cart-config
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  datasource:
    url: jdbc:h2:mem:TestDataBase;DATABASE_TO_UPPER=FALSE #jdbc:h2:file:./TestDataBase;DATABASE_TO_UPPER=FALSE
    name: comm
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        default_schema:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:password}
      timeout: 60000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
app:
  security:
    jwt:
      keystore-location: jwt-keystore.jks
      keystore-password: ${JWT_PASSWORD:password}
      key-alias: jwt-sign-key
      private-key-passphrase: ${JWT_PASSPHRASE:password}
logging:
  level:
    logging:
      level:
        root: INFO
    org:
      springframework:
        cache: INFO
    com:
      perficient:
        shoppingcart: INFO

config:
  security:
    jwt:
      issue: "E-commerce Cart Shopping"
      expiration: 900000
      claim: "roles"
