server:
  port: 8080
  address: 0.0.0.0

spring:
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecart
    name: ecart
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        default_schema:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: password
      timeout: 60000

app:
  security:
    jwt:
      keystore-location: jwt-keystore.jks
      keystore-password: password
      key-alias: jwt-sign-key
      private-key-passphrase: password

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    logging:
      level:
        root: INFO
    org:
      springframework:
        cache: INFO
    com:
      ecommerce: INFO
