spring:
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  datasource:
    url: jdbc:h2:file:./TestDataBase
    name: comm
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        default_schema:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
