name: Ecommerce Cart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
          unzip -d $HOME gradle-7.3-bin.zip
          export PATH=$HOME/gradle-7.3/bin:$PATH

      - name: Build with Gradle
        run: gradle build

      - name: Run tests
        run: gradle test

      - name: Generate artifact
        run: gradle assemble

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecommerce-cart
          path: build/libs/*.jar
